/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ExploBD.presentation.frames;

import java.sql.*;
import java.sql.Connection;   
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.ExploBD.data.DatabaseConnection;
import com.ExploBD.object.User;
import com.ExploBD.object.Place;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author iaziz
 */
public class DashboardRecommendation extends javax.swing.JFrame {
    
 
    private JScrollPane scrollPane;
    private DefaultTableModel tableModel;
  
    
    /**
     * Creates new form DashboardRceommendation
     */
    public DashboardRecommendation() {
       initComponents();
        
       loadUserData();
    }
    
       

    
      


    private void loadUserData() {
    DefaultTableModel      tableModel = (DefaultTableModel) tableRecommendation.getModel();  
        tableModel.setRowCount(0);

         

    try (Connection conn = DatabaseConnection.getConnection()) {
        String query = "SELECT username, min_budget, max_budget, travel_styles FROM users";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);
        boolean hasData = false;

        while (rs.next()) {
            hasData = true;
            
            String preference = rs.getString("travel_styles");
                if (preference == null || preference.trim().equalsIgnoreCase("faka")|| preference.trim().isEmpty()) {
                    preference = ""; 
                }else {
                preference = preference.trim();
            }
            
            tableModel.addRow(new Object[]{
                rs.getString("username"),
                rs.getInt("min_budget") + " - " + rs.getInt("max_budget"),
                preference,//place column empty enitially
                ""
            });
        }

        if (!hasData) {
            tableModel.addRow(new Object[]{"No user found", "", "", ""});
            
    }

    }catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading user data: " + e.getMessage());
        }
    }      

   
  


      
    
    
        private void generateRecommendation() {
    DefaultTableModel tableModel = (DefaultTableModel) tableRecommendation.getModel();

    for (int i = 0; i < tableModel.getRowCount(); i++) {

        String preference = (String) tableModel.getValueAt(i, 2);
        String place = "";

        if (preference != null) {

            preference = preference.trim().toLowerCase(); // ✅ VERY IMPORTANT

            if (preference.contains("historical")) {
                place = "Lalbagh Fort";
            } 
            else if (preference.contains("beach")) {
                place = "Cox's Bazar";
            } 
            else if (preference.contains("mountain")) {
                place = "Sajek Valley";
            } 
            else if (preference.isEmpty()) {
                place = ""; // faka hole blank
            } 
            else {
                place = "Dhaka";
            }
        }

        // ✅ JTable update
        tableModel.setValueAt(place, i, 3);
    }
}
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableRecommendation = new javax.swing.JTable();
        btnGenerateRec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableRecommendation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User", "Budget", "Preference", "Place"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRecommendation);

        btnGenerateRec.setText("Generate Recommendation");
        btnGenerateRec.addActionListener(this::btnGenerateRecActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnGenerateRec, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnGenerateRec)
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateRecActionPerformed
        // TODO add your handling code here:
         generateRecommendation();
    }//GEN-LAST:event_btnGenerateRecActionPerformed

                
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardRecommendation().setVisible(true));
   
    }

    // End of variables declaration                   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateRec;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRecommendation;
    // End of variables declaration//GEN-END:variables

}